#!/usr/bin/env python3
"""Rebuild Vault/Web Browsing/index.md from per-run search/extract files.

Idempotent: re-running regenerates the index from all files under
Firecrawl/Web Search and Firecrawl/Web Extract. Safe to run after every log.

Usage:
  python rebuild_index.py
  python rebuild_index.py --base "C:/Users/Tiger/Vault/Web Browsing"
"""
import os
import re
import sys
import datetime

DEFAULT_BASE = r"C:\Users\Tiger\Vault\Web Browsing"


def parse_fm(text):
    if not text.startswith('---'):
        return {}, text
    parts = text.split('---', 2)
    if len(parts) < 3:
        return {}, text
    fm = parts[1]
    body = parts[2]
    data = {}
    for line in fm.splitlines():
        m = re.match(r'\s*([A-Za-z_]+):\s*(.*)', line)
        if m:
            k = m.group(1).strip()
            v = m.group(2).strip().strip('"').strip("'")
            data[k] = v
    return data, body


def walk_md(folder, provider=''):
    out = []
    if not os.path.isdir(folder):
        return out
    for fn in sorted(os.listdir(folder)):
        if not fn.endswith('.md') or fn.lower() == 'index.md':
            continue
        p = os.path.join(folder, fn)
        try:
            with open(p, encoding='utf-8') as f:
                text = f.read()
        except Exception:
            continue
        fm, _ = parse_fm(text)
        fm['_file'] = fn[:-3]
        fm['_provider'] = provider
        out.append(fm)
    return out


def to_dt(fm, key):
    v = fm.get(key, '')
    if not v:
        return datetime.datetime.min
    if 'T' in v:
        cand = v[:19]
        for fmt in ('%Y-%m-%dT%H:%M:%S',):
            try:
                return datetime.datetime.strptime(cand, fmt)
            except Exception:
                pass
    for fmt in ('%d-%m-%Y',):
        try:
            return datetime.datetime.strptime(v[:10], fmt)
        except Exception:
            pass
    return datetime.datetime.min


def main():
    base = DEFAULT_BASE
    if len(sys.argv) > 2 and sys.argv[1] == '--base':
        base = sys.argv[2]
    # Provider-agnostic: each provider maps to (search_dir, extract_dir).
    providers = {
        'Firecrawl': ('Web Search', 'Web Extract'),
        'GroktoCrawl': ('Search', 'Answer'),
        'Exa': ('Search', 'Web Fetch'),
    }
    all_searches = []
    all_extracts = []
    counts = {}
    for prov, (sdir, edir) in providers.items():
        s = walk_md(os.path.join(base, prov, sdir), provider=prov)
        e = walk_md(os.path.join(base, prov, edir), provider=prov)
        all_searches.extend(s)
        all_extracts.extend(e)
        counts[prov] = (len(s), len(e))
    searches = all_searches
    extracts = all_extracts
    searches.sort(key=lambda x: to_dt(x, 'run_at'), reverse=True)
    extracts.sort(key=lambda x: to_dt(x, 'extracted_at'), reverse=True)

    today = datetime.date.today().strftime('%d-%m-%Y')
    L = []
    L.append('---')
    L.append('title: Web Browsing — Index')
    L.append('type: "[[Index]]"')
    L.append('domain: "[[Web Browsing]]"')
    L.append(f'created: {today}')
    L.append(f'updated: {today}')
    L.append('icon: TiWorld')
    L.append('iconColor: Silver')
    L.append('---')
    L.append('# Web Browsing — Index')
    L.append('')
    L.append('Searchable history of all web research via Hermes. Auto-logged per `web-browsing-log` skill. Regenerated by `rebuild_index.py` — do not hand-edit.')
    L.append('')
    L.append('## Structure')
    L.append('- [[Web Browsing/Firecrawl/Web Search]] — one file per `web_search`')
    L.append('- [[Web Browsing/Firecrawl/Web Extract]] — one file per `web_extract`')
    L.append('- [[Web Browsing/GroktoCrawl/Search]] — one file per `groktocrawl_search`')
    L.append('- [[Web Browsing/GroktoCrawl/Answer]] — one file per `groktocrawl_answer`')
    L.append('- [[Web Browsing/Exa/Search]] — one file per `web_search_exa`')
    L.append('- [[Web Browsing/Exa/Web Fetch]] — one file per `web_fetch_exa`')
    L.append('')
    L.append('## Recent Searches')
    for s in searches[:15]:
        title = s.get('title', s['_file'])
        rc = s.get('results_count', '?')
        cr = s.get('credits_used', '?')
        L.append(f"- [[{s['_file']}|{title}]] — {rc} results · {cr} credits · [[{s['_provider']}]]")
    if not searches:
        L.append('- (none yet)')
    L.append('')
    L.append('## Recent Extracts')
    for e in extracts[:15]:
        title = e.get('title', e['_file'])
        ps = e.get('parent_search', '')
        extra = f" — from {ps}" if ps else ""
        L.append(f"- [[{e['_file']}|{title}]] · [[{e['_provider']}]]{extra}")
    if not extracts:
        L.append('- (none yet)')
    L.append('')
    L.append('## By Provider')
    for prov, (sdir, edir) in providers.items():
        sc, ec = counts.get(prov, (0, 0))
        L.append(f'### {prov}')
        L.append(f"- {sdir}: {sc} files")
        L.append(f"- {edir}: {ec} files")
    L.append('')
    L.append('## All Entries (chronological)')
    for s in searches:
        title = s.get('title', s['_file'])
        L.append(f"- [[{s['_file']}|{title}]] (search) · [[{s['_provider']}]]")
    for e in extracts:
        title = e.get('title', e['_file'])
        L.append(f"- [[{e['_file']}|{title}]] (extract) · [[{e['_provider']}]]")
    if not searches and not extracts:
        L.append('- (no entries yet)')
    L.append('')

    out = os.path.join(base, 'index.md')
    with open(out, 'w', encoding='utf-8') as f:
        f.write('\n'.join(L) + '\n')
    total_s = sum(c[0] for c in counts.values())
    total_e = sum(c[1] for c in counts.values())
    print(f"Wrote {out}: {total_s} searches, {total_e} extracts")


if __name__ == '__main__':
    main()
